kind: pipeline
type: docker
name: prod
steps:
    - name: submodules
      image: alpine/git
      commands:
        - git submodule update --init --recursive

    - name: hugo build
      image: plugins/hugo
      settings:
        hugo_version: 0.110.0
        validate: false
        extended: true
        url: https://cantorgymnasium.de/
      commands:
        - apk add --update --no-cache tzdata
        - /bin/drone-hugo
    
    - name: deploy
      image: drillster/drone-rsync
      settings:
        hosts: [ "cantorgymnasium.de" ]
        port:
          from_secret: ssh_port
        user: web-push
        key:
          from_secret: ssh_key
        source: public/
        target: /opt/data/webdata/gcg-website/
        recursive: true
        delete: true

    - name: search index
      image: appleboy/drone-ssh
      settings:
        host:
          - cantorgymnasium.de
        username: web-push
        key: 
          from_secret: ssh_key
        port:
          from_secret: ssh_port
        command_timeout: 1m
        script:
          - /opt/data/webdata/gcg-website/
          - pagefind --source=.

    - name: notification
      image: appleboy/drone-telegram
      settings:
          token:
              from_secret: telegram_token
          to: 
              from_secret: telegram_room_id
      when:
          status:
              - success
              - failure

trigger:
    branch:
        - master
    event:
        - push
        - cron
        - rollback

---
kind: pipeline
type: docker
name: test
steps:
    - name: submodules
      image: alpine/git
      commands:
        - git submodule update --init --recursive
        
    - name: test build
      image: plugins/hugo
      settings:
        hugo_version: 0.110.0
        validate: false
        buildDrafts: true
        buildFuture: true
        extended: true
        output: test
        url: https://test.cantorgymnasium.de/
      commands:
        - apk add --update --no-cache tzdata
        - /bin/drone-hugo

    - name: deploy
      image: drillster/drone-rsync
      settings:
        hosts: [ "cantorgymnasium.de" ]
        port:
          from_secret: ssh_port
        user: web-push
        key:
          from_secret: ssh_key
        source: test/
        target: /opt/data/webdata/gcg-website-test/
        recursive: true
        delete: true

    - name: search index
      image: appleboy/drone-ssh
      settings:
        host:
          - cantorgymnasium.de
        username: web-push
        key: 
          from_secret: ssh_key
        port:
          from_secret: ssh_port
        command_timeout: 1m
        script:
          - /opt/data/webdata/gcg-website-test/
          - pagefind --source=.

trigger:
    branch:
        - master
    event:
        - push
        - cron
        - rollback

depends_on:
- prod