kind: pipeline
type: docker
name: dev
steps:
    - name: submodules
      image: alpine/git
      commands:
        - git submodule update --init --recursive

    - name: hugo build
      image: plugins/hugo
      settings:
        hugo_version: 0.110.0
        validate: false
        extended: true
        url: https://dev.cantorgymnasium.de/
      commands:
        - apk add --update --no-cache tzdata
        - /bin/drone-hugo
    
    - name: deploy
      image: drillster/drone-rsync
      settings:
        hosts: [ "cantorgymnasium.de" ]
        port:
          from_secret: ssh_port
        user: web-push
        key:
          from_secret: ssh_key
        source: public/
        target: /opt/data/webdata/gcg-website-dev/
        recursive: true
        delete: true

    - name: search index
      image: appleboy/drone-ssh
      settings:
        host:
          - cantorgymnasium.de
        username: web-push
        key: 
          from_secret: ssh_key
        port:
          from_secret: ssh_port
        command_timeout: 1m
        script:
          - /opt/data/webdata/gcg-website-dev/
          - pagefind --source=.

trigger:
    branch:
        - master
    event:
        - push
        - cron
        - rollback