image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive



pages:
  before_script:
  - apk add --update --no-cache openssh sshpass
  script:
  - hugo
  - sshpass -p $scp_password scp -oStrictHostKeyChecking=no -r public $scp_path
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH