baseURL: https://cantorgymnasium.de/
title: Georg-Cantor-Gymnasium
summaryLength: "10"
defaultContentLanguage: de
enableEmoji: true
enableRobotsTxt: true
timeZone: Europe/Berlin
removePathAccents: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
params:
  mobile: +49 345 6903156
  author: Georg-Cantor-Gymnasium Halle (Saale). Made with Educenter by Themefisher.
  logo: media/logo_lg_white.webp
  route_link: https://www.qwant.com/maps/place/osm:way:54033279@Georg-Cantor-Gymnasium
  address: Georg-Cantor-Gymnasium <br> Torstraße 13 <br> 06110 Halle (Saale)
  top_header: true
  email: schulleitung@cantor-gymnasium.de
  email_label: schulleitung(at)cantor-gymnasium.de
  description: Das Georg-Cantor-Gymnasium - eine
    mathematisch-naturwissenschaftliche Spezialschule in Halle (Saale).
  images:
    - media/zeichnung.webp
  impressumURL: pages/impressum
  dseURL: pages/datenschutz
  copyright: "Georg-Cantor-Gymnasium Halle (Saale). Made with :heart: and
    [Hugo](https://gohugo.io)."
  plugins:
    css:
      - https://assets.cantorgymnasium.de/bootstrap/v5/css/bootstrap.min.css
      - https://assets.cantorgymnasium.de/slick/v1.8/slick.css
      - https://assets.cantorgymnasium.de/venobox/v2/dist/venobox.min.css
      - https://assets.cantorgymnasium.de/fonts/fira/fira.min.css
      - https://assets.cantorgymnasium.de/fonts/ubuntu/ubuntu.min.css
      - /pagefind/pagefind-ui.css
    js:
      - https://assets.cantorgymnasium.de/bootstrap/v5/js/bootstrap.bundle.min.js
      - https://assets.cantorgymnasium.de/slick/v1.8/slick.min.js
      - https://assets.cantorgymnasium.de/lazyload/v17/dist/lazyload.min.js
      - /pagefind/pagefind-ui.js
    head_js:
      - https://assets.cantorgymnasium.de/jquery/v3.7/jquery.min.js
      - https://assets.cantorgymnasium.de/venobox/v2/dist/venobox.min.js
      - https://assets.cantorgymnasium.de/shuffle/v6/shuffle.min.js
  social:
    - title: YouTube
      icon: youtube
      link: https://www.youtube.com/@cantornews
    - title: Twitter
      icon: twitter
      link: https://twitter.com/cantor_news
    - title: Instagram
      icon: instagram
      link: https://instagram.com/cantor.news
    - title: Facebook
      icon: facebook
      link: https://facebook.com/cantor.news
  preloader:
    enable: true
    preloader: media/logo_lg_white.webp
    loader: media/load.svg
menu:
  main:
    - name: Aktuelles
      URL: blog
      weight: 1
      hasChildren: false
      params:
        external: false
        separator: false
    - name: Schule
      weight: 2
      hasChildren: true
      params:
        external: false
        separator: false
    - parent: Schule
      name: Über die Schule
      URL: about
      weight: 1
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Schule
      name: Ganztagsbereich
      URL: ganztagsangebote
      weight: 2
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Schule
      name: Termine
      URL: termine
      weight: 3
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Schule
      name: Aufnahme
      URL: anmeldung
      weight: 4
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Schule
      name: Schulbibliothek
      URL: pages/bibo
      weight: 5
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Schule
      name: Schulchronik
      URL: schulchronik
      weight: 6
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Schule
      name: Cantorpreis
      URL: cantorpreis
      weight: 7
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Schule
      name: Virtueller Rundgang
      URL: https://vr.cantorgymnasium.de/tour/
      weight: 8
      hasChildren: false
      params:
        external: true
        separator: false
    - weight: 3
      name: Unterricht
      hasChildren: true
      params:
        external: false
        separator: false
    - parent: Unterricht
      name: Wettbewerbe
      URL: wettbewerbe
      weight: 4
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Unterricht
      name: Begabtenförderung
      URL: begabte
      weight: 5
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Unterricht
      name: Junior-Ingenieur-Akademie
      URL: pages/jia
      weight: 6
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Unterricht
      name: Projektwoche
      URL: projektwoche
      weight: 7
      hasChildren: false
      params:
        external: false
        separator: false
    - name: Für Schüler und Eltern
      weight: 4
      hasChildren: true
      params:
        external: false
        separator: false
    - parent: Für Schüler und Eltern
      name: Dokumente und Formulare
      URL: forms
      weight: 1
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Für Schüler und Eltern
      name: Vertretungsplan
      URL: https://stundenplan24.de/20072021/mobil/
      weight: 2
      hasChildren: false
      params:
        external: true
        separator: false
    - parent: Für Schüler und Eltern
      name: Lernplattform Moodle
      URL: https://moodle.bildung-lsa.de/gcg
      weight: 3
      hasChildren: false
      params:
        external: true
        separator: true
    - parent: Für Schüler und Eltern
      name: Essensbestellung
      URL: https://heideklause-halle.de/bestellung/
      weight: 4
      hasChildren: false
      params:
        external: true
        separator: false
    - name: Schülerzeitung
      weight: 5
      parent: Für Schüler und Eltern
      URL: https://schuelerzeitung-gcg.de
      params:
        external: true
        separator: false
      hasChildren: false
    - hasChildren: false
      params:
        external: true
        separator: true
      name: Schulshop
      weight: 6
      parent: Für Schüler und Eltern
      URL: https://cantor-shop.migoma.de
    - parent: Für Schüler und Eltern
      name: Förderverein
      URL: pages/foerderverein
      weight: 7
      hasChildren: false
      params:
        external: false
        separator: false
    - parent: Für Schüler und Eltern
      name: Schülervertretung
      URL: pages/schuelervertretung
      weight: 8
      hasChildren: false
      params:
        external: false
        separator: false
    - name: Elternvertretung
      weight: 9
      URL: pages/elternvertretung
      parent: Für Schüler und Eltern
      hasChildren: false
      params:
        external: false
        separator: false
    - name: Kontakt
      URL: kontakt
      weight: 5
      hasChildren: false
      params:
        external: false
        separator: false
  footer:
    - name: Termine
      URL: termine
    - name: Anmeldung
      URL: anmeldung
    - name: Dokumente und Formulare
      URL: forms
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
  vimeo:
    enableDNT: true
module:
  imports:
    - path: github.com/hugomods/icons/vendors/mdi
build:
  noJSConfigInAssets: true
