name: Website Prod/Test

on:
  push:
    branches: [main]
  schedule:
    - cron: '@daily'
  workflow_dispatch:

defaults:
  run:
    working-directory: /opt/runner/workdir/gcg-website-main

jobs:
  prod-build:
    name: Produktivumgebung
    if: gitea.repository == 'gcg/gcg-website'
    runs-on: act-runner-user
    steps:
      - name: Pull
        run: |
          git fetch --all
          git reset --hard origin/main
          git lfs pull
      - name: Build
        run: |
          rm -rf public
          hugo --minify --gc --baseURL "https://cantorgymnasium.de/"
      - name: Deploy
        run: |
          cd public
          pagefind_extended --site=. 
          rsync -azr --delete ./ /opt/data/webdata/gcg-website/
      - name: Notification
        uses: actions/telegram-action@main
        if: always()
        with:
          chat_id: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}
  test-build:
    name: Testumgebung
    if: gitea.repository == 'gcg/gcg-website'
    runs-on: act-runner-user
    steps:
      - name: Pull
        run: |
          git fetch --all
          git reset --hard origin/main
          git lfs pull
      - name: Build
        run: |
          rm -rf test
          hugo --minify --gc --baseURL "https://test.cantorgymnasium.de/" --buildDrafts --buildFuture -d test
      - name: Deploy
        run: |
          cd test
          rsync -azr --delete ./ /opt/data/webdata/gcg-website-test/
