name: hugo build

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: act-runner
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"

      - name: deploy
        uses: up9cloud/action-rsync@master
        env:
          HOST: cantorgymnasium.de
          KEY: ${{ secrets.WEB_PUSH_KEY }}
          TARGET: /opt/data/webdata/gcg-website/dev-test/
          USER: web-push
          ARGS: -avzr --delete
          SSH_ARGS: '-p 1845 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: ./public/
          POST_SCRIPT: "cd /opt/data/webdata/gcg-website/ && pagefind --source=."

      - name: notification
        uses: https://github.com/yamaks2306/telegram-notification@main
        if: always()
        with:
          chat_id: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}