name: hugo build

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: act-runner
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"
    
      - name: deploy
        uses: https://github.com/burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: /opt/data/webdata/gcg-website/dev-test/
          remote_host: cantorgymnasium.de
          remote_user: web-push
          remote_port: ${{ secrets.WEB_PUSH_PORT }}
          remote_key: ${{ secrets.WEB_PUSH_KEY }}
        
      - name: search index
        uses: https://github.com/JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.WEB_PUSH_HOST }}
          privateKey: ${{ secrets.WEB_PUSH_KEY }}
          command: |
            cd /opt/data/webdata/gcg-website/
            pagefind --source=.

      - name: notification
        uses: https://github.com/yamaks2306/telegram-notification@main
        if: always()
        with:
          chat_id: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}