name: website-main

on:
  push:
    branches:
      - master
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ gitea.workflow }}-${{ gitea.ref }}
  cancel-in-progress: true

jobs:
  prod-build:
    if: gitea.repository == 'gcg/gcg-website' && gitea.event_name == 'push'
    runs-on: act-runner-user
    timeout-minutes: 5
    steps:
      - name: pull
        run: |
          cd /opt/data/actions/gcg-website-master
          git fetch --all
          git reset --hard origin/master
      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"
      - name: deploy
        run: |
          cd public
          pagefind --source=. 
          rsync -azr --delete ./ /opt/data/webdata/gcg-website/
      - name: notification
        uses: actions/telegram-action@main
        if: always()
        with:
          chat_id: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}
          include_commit_info: false
  test-build:
    if: gitea.repository == 'gcg/gcg-website' && gitea.event_name == 'push'
    runs-on: act-runner-user
    timeout-minutes: 5
    steps:
      - name: pull
        run: |
          cd /opt/data/actions/gcg-website-master
          git fetch --all
          git reset --hard origin/master
      - name: build
        run: hugo --minify --gc --baseURL "https://test.cantorgymnasium.de/" --buildDrafts --buildFuture -d test
      - name: deploy
        run: |
          cd test
          rsync -azr --delete ./ /opt/data/webdata/gcg-website-test/
  auto-rebuild:
    if: gitea.repository == 'gcg/gcg-website' && gitea.event_name == 'schedule'
    runs-on: act-runner-user
    timeout-minutes: 5
    steps:
      - name: pull
        run: |
          cd /opt/data/actions/gcg-website-master
          git fetch --all
          git reset --hard origin/master
      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"
      - name: deploy
        run: |
          cd public
          pagefind --source=. 
          rsync -azr --delete ./ /opt/data/webdata/gcg-website/
