name: website-main

on:
  push:
    branches:
      - master
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prod-build:
    if: github.repository == 'gcg/gcg-website' && github.event_name == 'push'
    runs-on: act-runner-user
    timeout-minutes: 5
    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.2'
          extended: true

      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"

      - name: deploy
        run: |
          cd public
          pagefind --source=. 
          rsync -azr --delete ./ /opt/data/webdata/gcg-website/

      - name: notification
        uses: https://github.com/yamaks2306/telegram-notification@main
        if: always()
        with:
          chat_id: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}
          include_commit_info: false
  test-build:
    if: github.repository == 'gcg/gcg-website' && github.event_name == 'push'
    runs-on: act-runner-user
    timeout-minutes: 5
    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.2'
          extended: true

      - name: build
        run: hugo --minify --gc --baseURL "https://test.cantorgymnasium.de/" --buildDrafts --buildFuture -d test

      - name: deploy
        run: |
          cd test
          pagefind --source=. 
          rsync -azr --delete ./ /opt/data/webdata/gcg-website-test/
  auto-rebuild:
    if: github.repository == 'gcg/gcg-website' && github.event.issue.number == 219
    runs-on: act-runner-user
    timeout-minutes: 5
    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.2'
          extended: true

      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"

      - name: deploy
        run: |
          cd public
          pagefind --source=. 
          rsync -azr --delete ./ /opt/data/webdata/gcg-website/
