name: hugo build

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: docker://act-runner
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"

      - name: deploy
        uses: https://git.cantorgymnasium.de/gcg/rsync-deploy-action@main
        with:
          HOST: cantorgymnasium.de
          PORT: ${{secrets.WEB_PUSH_PORT }}
          USER: web-push
          PRIVATE_SSH_KEY: ${{secrets.WEB_PUSH_KEY }}
          REPOSITORY_PATH: public/
          SERVER_PATH: /opt/data/webdata/gcg-website-gt/

      - name: search index
        uses: https://github.com/JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.WEB_PUSH_HOST }}
          privateKey: ${{ secrets.WEB_PUSH_KEY }}
          command: |
            cd /opt/data/webdata/gcg-website/
            pagefind --source=.   

      - name: notification
        uses: https://github.com/yamaks2306/telegram-notification@main
        if: always()
        with:
          chat_id: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}