name: hugo build

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.repository == 'gcg/gcg-website'
    runs-on: act-runner-user
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.2'
          extended: true

      - name: build
        run: hugo --minify --gc --baseURL "https://cantorgymnasium.de/"

      - name: deploy
        run: |
          cd public
          pagefind --source=. 
          rsync -azr --delete ./ /opt/data/webdata/gcg-website-gt/

      - name: notification
        uses: https://github.com/yamaks2306/telegram-notification@main
        if: always()
        with:
          chat_id: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}