# backend:
#   name: github
#   repo: eesev9ie/gcg-website
#   branch: master
#   site_domain: eesev9ie.netlify.app

backend:
  name: gitlab
  repo: cantortechnik/gcg-website
  branch: master
  auth_type: pkce
  app_id: f9d3e269912cc9560d183167726afc7ccb517862904d0a6c0b10105719964bab
  api_root: https://gitlab.cantorgymnasium.de/api/v4
  base_url: https://gitlab.cantorgymnasium.de
  auth_endpoint: oauth/authorize
  ##base_url: http://localhost:8000

media_folder: "static/media"
public_folder: "/media"
site_url: https://eesev9ie.github.io
display_url: https://eesev9ie.github.io
logo_url: /media/logo_y.svg
locale: "de"
publish_mode: editorial_workflow
show_preview_links: false

collections:
  - name: "pages-de"
    label: "Statische Seiten"
    editor:
      preview: true
    files:
      - name: "blog-index"
        label: "Blog"
        file: "content/german/blog/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - name: "about-index"
        label: "Über die Schule"
        file: "content/german/about/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
          - {label: "Text", name: "body", widget: "markdown"}
      - name: "anmeldung-index"
        label: "Anmeldung"
        file: "content/german/anmeldung/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
          - {label: "Text", name: "body", widget: "markdown"}
      - name: "cantorpreis-index"
        label: "Cantor-Preis"
        file: "content/german/cantorpreis/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - name: "contact-index"
        label: "Kontakt"
        file: "content/german/kontakt/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
          - {label: "Text", name: "body", widget: "markdown"}
      - name: "event-index"
        label: "Termine"
        file: "content/german/termine/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
          - label: Termine
            label_singular: " "
            name: "events"
            widget: "list"
            fields:
              - {label: "Titel", name: "title", widget: "string", required: true}
              - {label: "Datum", name: "date", widget: "datetime",  required: true, date_format: "DD.MM.YYYY", time_format: "HH:mm"}
              - {label: "Ort", name: "location", widget: "string", required: true}
              - {label: "Beschreibung", name: "summary", widget: "string", required: false}
            required: false

      - name: "forms-index"
        label: "Formulare und Vorlagen"
        file: "content/german/forms/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - name: "ganztagsangebote-index"
        label: "Ganztagsangebote"
        file: "content/german/ganztagsangebote/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - name: "impressum"
        label: "Impressum"
        file: "content/german/impressum/index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Type", name: "type", widget: "hidden", default: "pages"}
          - {label: "Type", name: "layout", widget: "hidden", default: "single.html"}
          - {label: "Text", name: "body", widget: "markdown"}
      - name: "wettbewerbe-index"
        label: "Wettbewerbe"
        file: "content/german/wettbewerbe/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - name: "schuelerrat-index"
        label: "Schülerrat"
        file: "content/german/schuelerrat/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
          - {label: "Text", name: "body", widget: "markdown", required: false}
      - name: "schuelerrat-geschaeftsordnung"
        label: "Geschäftsordnung Schülerrat"
        file: "content/german/schuelerrat/geschaeftsordnung.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
          - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
          - {label: "Text", name: "body", widget: "markdown", required: false}
  - name: "author-de" # Used in routes, e.g., /admin/collections/blog
    label: "Autor*innen" # Used in the UI
    label_singular: "Autor*in"
    folder: "content/german/author" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
     preview: false
    media_folder: '/static/media/people'
    public_folder: '/media/people'
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Metabeschreibung", name: "description", widget: "text", default: "", required: false}
      - {label: "Gravatar-E-Mail", name: "email", widget: "string", required: false}
      - {label: "Foto", name: "image", widget: "image"}
      - label: "Kontaktdaten"
        label_singular: " "
        name: "social"
        widget: "list"
        fields:
          - {label: "Titel", name: "title", widget: "string", required: false}
          - label: "Symbol"
            name: "icon"
            widget: "select"
            options:
              - { label: "Flickr", value: "ti-flickr" }
              - { label: "Tumblr", value: "ti-tumblr" }
              - { label: "YouTube", value: "ti-youtube" }
              - { label: "Twitter", value: "ti-twitter-alt" }
              - { label: "Pinterest", value: "ti-pinterest" }
              - { label: "GitHub", value: "ti-github" }
              - { label: "StackOverflow", value: "ti-stack-overflow" }
              - { label: "Vimeo", value: "ti-vimeo" }
              - { label: "Instagram", value: "ti-instagram" }
              - { label: "Facebook", value: "ti-facebook" }
              - { label: "SoundCloud", value: "ti-soundcloud" }
              - { label: "Reddit", value: "ti-reddit" }
              - { label: "Skype", value: "ti-skype" }
              - { label: "LinkedIn", value: "ti-linkedin" }
              - { label: "E-Mail", value: "ti-email" }
              - { label: "Sonstige", value: "ti-sharethis" }
          - {label: "Link", name: "link", widget: "string"}
        required: false
      - {label: "Beschreibung", name: "body", widget: "markdown"}
  - name: "blog-de"
    label: "Blogbeiträge"
    label_singular: "Blogbeitrag"
    folder: "content/german/blog"
    filter: {field: "type", value: "post"}
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    media_folder: '/static/media/blog'
    public_folder: '/media/blog'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Metabeschreibung", name: "description", widget: "text", default: "", required: false}
      - {label: "Beitragsbild", name: "image", widget: "image", default: "/media/image.png"}
      - label: "Beitragsautor"
        name: "author"
        widget: "relation"
        collection: "author-de"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
      - label: "Kategorien"
        name: "categories"
        widget: "list"
        required: false
        field: {label: "Kategorie", name: "category", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: {label: "Tag", name: "tag", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "forms-de"
    label: "Formulare und Vorlagen"
    label_singular: "Formular"
    description: "Hier sind Formulare, Vorlagen und andere Dokumente zu hinterlegen."
    folder: "content/german/forms"
    filter: {field: "type", value: "forms"}
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    media_folder: '/static/media/forms'
    public_folder: '/media/forms'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "forms"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "anmeldung-de"
    label: "Anmeldung"
    label_singular: "Anmeldeinformation"
    folder: "content/german/anmeldung"
    filter: {field: "type", value: "anmeldung"}
    create: true
    editor:
      preview: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "anmeldung"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "cantorpreis-de"
    label: "Cantor-Preisträger*in"
    folder: "content/german/cantorpreis"
    filter: {field: "type", value: "cantorpreis"}
    create: true
    editor:
      preview: false
    media_folder: '/static/media/cantorpreis'
    public_folder: '/media/cantorpreis'
    fields:
      - {label: "Jahr", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Beschreibung", name: "description", widget: "text", required: false}
      - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
      - {label: "Name", name: "name", widget: "string"}
      - label: "Kontaktdaten/Soz. Netzwerke"
        name: "contact"
        widget: "list"
        fields:
          - {label: "Name/Adresse/Telefonnummer", name: "name", widget: "string"}
          - {label: "Symbol", name: "icon", widget: "string", hint: "Symbolname von https://themify.me/themify-icons"}
          - {label: "Link", name: "link", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "cantorpreis"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "ganztagsangebote-de"
    label: "Ganztagsangebote"
    label_singular: "Ganztagsangebot"
    folder: "content/german/ganztagsangebote"
    filter: {field: "type", value: "ganztagsangebote"}
    create: true
    editor:
      preview: false
    media_folder: '/static/media/ganztagsangebote'
    public_folder: '/media/ganztagsangebote'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
      - {label: "Themenbereiche", name: "categories_ag", widget: "string"}
      - {label: "Dauer", name: "weekly", widget: "string"}
      - {label: "Tag/Stunden", name: "duration", widget: "string"}
      - {label: "Klassenstufen", name: "class", widget: "string"}
      - {label: "Raum", name: "root", widget: "string"}
      - {label: "Anmeldelink", name: "apply_url", widget: "hidden", default: "https://moodle.bildung-lsa.de/gcg/mod/choice/view.php?id=828"}
      - {label: "Type", name: "type", widget: "hidden", default: "ganztagsangebote"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "wettbewerbe-de"
    label: "Wettbewerbe"
    label_singular: "Wettbewerb"
    folder: "content/german/wettbewerbe"
    filter: {field: "type", value: "wettbewerbe"}
    create: true
    editor:
      preview: false
    media_folder: '/static/media/contests'
    public_folder: '/media/people/contests'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
      - {label: "Fach", name: "category", widget: "string"}
      - {label: "Klassenstufen", name: "class", widget: "string"}
      - {label: "Website", name: "web_url", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "wettbewerbe"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "schulchronik"
    label: "Schulchronik"
    label_singular: "Chronikjahr"
    folder: "content/german/schulchronik"
    filter: {field: "type", value: "schulchronik"}
    create: true
    #editor:
      #preview: false
    media_folder: '/static/media/schulchronik'
    public_folder: '/media/schulchronik'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "schulchronik"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "abiturienten"
    label: "Abiturienten"
    label_singular: "Abiturjahrgang"
    folder: "content/german/abiturienten"
    filter: {field: "type", value: "abiturienten"}
    create: true
    editor:
      preview: false
    media_folder: '/static/media/abiturienten'
    public_folder: '/media/abiturienten'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: "false", required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Bild", name: "image", widget: "image", default: "/media/image.png", required: false}
      - {label: "Mehrere Bilder", name: "few", widget: "boolean", default: "false", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "abiturienten"}
      - {label: "Text", name: "body", widget: "markdown"}
