backend:
  name: gitea
  repo: gcg/gcg-website
  branch: master
  api_root: https://git.cantorgymnasium.de/api/v1
  base_url: https://oauth.cantorgymnasium.de
  commit_messages:
    create: "{{collection}} {{slug}} erstellt"
    update: "{{collection}} {{slug}} aktualisiert"
    delete: "{{collection}} {{slug}} gelöscht"
    uploadMedia: "{{path}} hochgeladen"
    deleteMedia: "{{path}} gelöscht"

local_backend: true

media_folder: "/static/media/schulchronik"
public_folder: "/media/schulchronik"
site_url: https://cantorgymnasium.de/schulchronik/
display_url: https://cantorgymnasium.de/schulchronik/
locale: "de"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

show_preview_links: false

collections:
  - name: "index-pages"
    icon: "page"
    label: "Übersichten"
    editor:
      preview: true
      frame: true
    files:
      - name: "cantorpreis-index"
        label: "Cantorpreis"
        file: "content/german/cantorpreis/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inaktiv", name: "draft", widget: "boolean", default: false, required: false, hint: "Diese Einstellung deaktiviert den Bereich auf der Website."}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
          - {label: "Einleitung", name: "description", widget: "text", required: false}
      - name: "abiturienten"
        label: "Abiturienten"
        file: "content/german/abiturienten/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inaktiv", name: "draft", widget: "boolean", default: false, required: false, hint: "Diese Einstellung deaktiviert den Bereich auf der Website."}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
          - {label: "Einleitung", name: "description", widget: "text", required: false}
      - name: "cantorfora"
        label: "Cantorfora"
        file: "content/german/cantorfora/_index.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inaktiv", name: "draft", widget: "boolean", default: false, required: false, hint: "Diese Einstellung deaktiviert den Bereich auf der Website."}
          - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
          - {label: "Einleitung", name: "description", widget: "text", required: false}
          
          - {label: "Text", name: "body", widget: "markdown", required: false}
  - name: "chronikseiten"
    icon: "page-add"
    label: "Inhalt"
    label_singular: "Seite"
    folder: "content/german/chronikseiten"
    create: true
    editor:
      preview: true
      frame: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
      - {label: "Metabeschreibung", name: "description", widget: "text", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "pages"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "single.html"}
      
      - label: "Aliase"
        name: "aliases"
        widget: "list"
        required: false
        fields:
          - label: "Alias"
            name: "alias"
            widget: "string"
      - {label: "Text", name: "body", widget: "markdown", required: false}
  - name: "statistik"
    icon: "stats"
    label: "Statistik"
    editor:
      preview: false
    files:
      - name: "abiturdurchschnitte"
        label: "Abiturdurchschnitte"
        file: "static/data/abiturdurchschnitte.json"
        fields:
          - label: "Abiturdurchschnitte"
            label_singular: "Abiturdurchschnitt"
            name: "abiturdurchschnitte"
            widget: "list"
            required: false
            fields:
              - {label: "Jahr", name: "jahr", widget: "number", required: true}
              - {label: "Schnitt", name: "schnitt", widget: "number", value_type: "float", step: 0.01, required: true}
      - name: "schuelerzahlen"
        label: "Schülerzahlen"
        file: "static/data/schuelerzahlen.json"
        fields:
          - label: "Schülerzahlen"
            label_singular: "Schülerzahlen"
            name: "schuelerzahlen"
            widget: "list"
            required: false
            fields:
              - {label: "Jahr", name: "year", widget: "number", required: true}
              - {label: "Gesamt", name: "all", widget: "number", required: true}
              - {label: "davon Mädchen", name: "girls", widget: "number", required: true}
  - name: "cantorpreis"
    icon: "award"
    label: "Cantorpreisträger"
    label_singular: "Cantorpreisträger"
    folder: "content/german/cantorpreis"
    filter: {field: "type", value: "cantorpreis"}
    sortable_fields:
      fields: ['title', 'name']
      default:
        field: title
        direction: Descending
    summary: "{{title}} - {{name}}"
    create: true
    editor:
      preview: false
    media_folder: '/static/media/cantorpreis'
    public_folder: '/media/cantorpreis'
    fields:
      - {label: "Jahr", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
      - {label: "Beschreibung", name: "description", widget: "text", required: false}
      - {label: "Bild", name: "image", widget: "image", default: "/media/cantorpreis/image.webp", required: false, media_library: { config: { max_file_size: 2048000 } } }
      - {label: "Name", name: "name", widget: "string"}
      - label: "Kontaktdaten/Soz. Netzwerke"
        name: "contact"
        widget: "list"
        required: false
        fields:
          - {label: "Bezeichnung", name: "name", widget: "string"}
          - label: "Symbol"
            name: "icon"
            widget: "select"
            options:
              - { label: "YouTube", value: "mdi mdi-youtube" }
              - { label: "Twitter", value: "mdi mdi-twitter" }
              - { label: "Pinterest", value: "mdi mdi-pinterest" }
              - { label: "GitHub", value: "mdi mdi-github" }
              - { label: "Git", value: "mdi mdi-git" }
              - { label: "Vimeo", value: "mdi mdi-vimeo" }
              - { label: "Instagram", value: "mdi mdi-instagram" }
              - { label: "Facebook", value: "mdi mdi-facebook" }
              - { label: "Linkedin", value: "mid mdi-linkedin" }
              - { label: "E-Mail", value: "mdi mdi-at" }
              - { label: "Sonstige", value: "mdi mdi-share-variant-outline" }
          - {label: "Link", name: "link", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "cantorpreis"}
      
      - {label: "Text", name: "body", widget: "markdown", required: false}
  - name: "superhaufen"
    icon: "superhaufen"
    label: "Superhaufen"
    label_singular: "Superhaufen"
    folder: "content/german/superhaufen"
    filter: {field: "type", value: "superhaufen"}
    create: true
    editor:
      preview: false
    media_folder: '/static/media/superhaufen'
    public_folder: '/media/superhaufen'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
      - {label: "Type", name: "type", widget: "hidden", default: "superhaufen"}
      
      - label: "Rückverlinkung"
        name: "previous"
        widget: "object"
        fields:
          - {label: "Aktiviert", name: "enable", widget: "hidden", default: true}
          - {label: "Titel", name: "title", widget: "string", required: true}
          - {label: "Link", name: "link", widget: "string", required: true}
      - label: "Kacheln"
        name: "tiles"
        widget: "list"
        required: false
        fields:
          - {label: "Titel", name: "title", widget: "string", required: true}
          - {label: "Hintergrundfarbe", name: "bg_color", widget: "color", required: true}
          - {label: "Symbol", name: "icon", widget: "string", required: true}
          - {label: "Symbolfarbe", name: "font_color", widget: "color", required: true}
          - {label: "Inhalt", name: "content", widget: "markdown", required: true}
          - label: "Unter-Unterhaufen"
            name: "unterhaufen"
            widget: "list"
            required: false
            fields:
              - {label: "Titel", name: "title", widget: "string", required: false}
              - {label: "Inhalt", name: "content", widget: "markdown", required: true}
  - name: "schulchronik"
    icon: "pillar"
    label: "Schulchronik"
    label_singular: "Chronikjahr"
    folder: "content/german/schulchronik"
    filter: {field: "type", value: "schulchronik"}
    create: true
    editor:
      preview: false
    media_folder: '/static/media/schulchronik'
    public_folder: '/media/schulchronik'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
      - {label: "Type", name: "type", widget: "hidden", default: "schulchronik"}
      - {label: "Einleitung", name: "pretext", hint: "Jahreszahltext", widget: "markdown", required: false}
      - label: "Kreative Haufen"
        name: "topics"
        widget: "list"
        required: false
        fields:
          - {label: "Titel", name: "title", widget: "string", required: true}
          - {label: "Inhalt", name: "content", widget: "markdown", required: true}
          - label: "Superhaufen"
            name: "superhaufen"
            widget: "object"
            required: false
            fields:
              - {label: "Aktiviert", name: "enable", widget: "boolean", required: false}
              - label: "Superhaufen"
                name: "link"
                widget: "relation"
                collection: "superhaufen"
                search_fields: ["title"]
                value_field: "title"
                required: false
                collapsed: true
      - label: "Cantorpreisträger"
        name: "cantorpreisträger"
        widget: "relation"
        collection: "cantorpreis"
        search_fields: ["jahr", "name"]
        value_field: "name"
        required: false
      
      - {label: "Text", name: "body", widget: "markdown", required: false, default: ""}
  - name: "abiturienten"
    icon: "graduation-cap"
    label: "Abiturienten"
    label_singular: "Abiturjahrgang"
    folder: "content/german/abiturienten"
    filter: {field: "type", value: "abiturienten"}
    create: true
    editor:
      preview: false
    media_folder: '/static/media/abiturienten'
    public_folder: '/media/abiturienten'
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
      - {label: "Bild", name: "image", widget: "image", default: "/media/abiturienten/image.webp", required: false, media_library: { config: { max_file_size: 2048000 } } }
      - {label: "Mehrere Bilder", name: "multiple", widget: "boolean", default: false, required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "abiturienten"}
      
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "cantorfora"
    icon: "presentation"
    label: "Cantorfora"
    label_singular: "Cantorforum"
    folder: "content/german/cantorfora"
    filter: {field: "type", value: "cantorfora"}
    create: true
    slug: "{{slug}}"
    editor:
     preview: true
     frame: true
    media_folder: '/static/media/cantorfora'
    public_folder: '/media/cantorfora'
    view_groups:
      - label: Drafts
        field: draft
    sortable_fields:
      fields: ['index', 'title']
      default:
        field: index
        direction: Ascending
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Laufindex", name: "index", widget: "number", value_type: 'int', min: 1, step: 1, required: true, hint: "Nummer des Cantorforums"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.webp"}
      - {label: "Metabeschreibung", name: "description", widget: "text", default: "", required: false}
      - {label: "Beitragsbild", name: "image", widget: "image", default: "/media/image.webp", media_library: { config: { max_file_size: 2048000 } } }
      - {label: "Type", name: "type", widget: "hidden", default: "cantorfora"}
      
      - {label: "Text", name: "body", widget: "markdown"}
