on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Hugo to GitHub Pages
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.TOKEN }}
          cname:
          branch: master
          repo: eesev9ie/eesev9ie.github.io
          hugoVersion: 0.95.0
          args: --gc --minify --cleanDestinationDir
